### ISSUE TITLE
Persisting into Cassandra second time

### ISSUE THREAD

**Issue by utkarshdeep** [oscerd/camel-cassandra-example#1]
I wrote a camel route to poll files from FTP server and then persisting an entity into cassandra. It worked fine the first time the route got executed, but when the route got invoked the second time, it throws some error. Below I am appending the code and the error:
**CODE**
`PropertiesComponent pc = getContext().getComponent("properties", PropertiesComponent.class);
pc.setLocation("classpath:ftp.properties");
HashMap<String, Object> insert = new HashMap<String, Object>();
insert.put("id", UUID.randomUUID());
insert.put("name", "utkarsh0");
String cassandraAddress = "127.0.0.1";
List<String> collAddr = new ArrayList<String>();
collAddr.add(cassandraAddress);
getContext().getShutdownStrategy().setTimeout(10);
from("{{ftp.server}}")
.to("file:target/download")
.log("Downloaded file ${file:name} complete.")
.setHeader(CassandraConstants.CASSANDRA_CONTACT_POINTS, constant(collAddr))
.setBody(constant(""))
.setHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT, constant(insert))
.to("cassandra:cassandraConnection?keyspace=simplex&table=test&operation=insert")
.removeHeader(CassandraConstants.CASSANDRA_INSERT_OBJECT);`

**ERROR**
2018-01-16 00:21:44,052 [alhost:21/files] ERROR DefaultErrorHandler            - Failed delivery for (MessageId: ID-utkarsh-1516042220798-0-5 on ExchangeId: ID-utkarsh-1516042220798-0-4). Exhausted after delivery attempt: 1 caught: com.github.oscerd.component.cassandra.CassandraException: com.datastax.driver.core.exceptions.SyntaxError: line 1:18 no viable alternative at input ')' (INSERT INTO test ([)]...)

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route1            ] [route1            ] [ftp://localhost:21/files?delay=5s&move=done&password=xxxxxx&username=sammy    ] [      2316]
[route1            ] [to1               ] [file:target/download                                                          ] [         1]
[route1            ] [log1              ] [log                                                                           ] [         0]
[route1            ] [setHeader1        ] [setHeader[CamelCassandraContactPoints]                                        ] [         1]
[route1            ] [setBody1          ] [setBody[constant{}]                                                           ] [         0]
[route1            ] [setHeader2        ] [setHeader[CamelCassandraInsertObject]                                         ] [         0]
[route1            ] [to2               ] [cassandra:cassandraConnection?keyspace=simplex&table=test&operation=insert    ] [      2312]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
com.github.oscerd.component.cassandra.CassandraException: com.datastax.driver.core.exceptions.SyntaxError: line 1:18 no viable alternative at input ')' (INSERT INTO test ([)]...)
	at com.github.oscerd.component.cassandra.CassandraComponent.wrapInCamelCassandraException(CassandraComponent.java:50) ~[camel-cassandra-2.17.0.jar:?]
	at com.github.oscerd.component.cassandra.CassandraProducer.process(CassandraProducer.java:111) ~[camel-cassandra-2.17.0.jar:?]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.processor.SendProcessor$2.doInAsyncProducer(SendProcessor.java:178) ~[camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:445) ~[camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:173) ~[camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:176) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:452) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.component.file.remote.RemoteFileConsumer.processExchange(RemoteFileConsumer.java:137) [camel-ftp-2.20.1.jar:2.20.1]
	at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:219) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:183) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.20.1.jar:2.20.1]
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.20.1.jar:2.20.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:18 no viable alternative at input ')' (INSERT INTO test ([)]...)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:63) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.github.oscerd.component.cassandra.CassandraProducer.doInsert(CassandraProducer.java:351) ~[camel-cassandra-2.17.0.jar:?]
	at com.github.oscerd.component.cassandra.CassandraProducer.invokeOperation(CassandraProducer.java:150) ~[camel-cassandra-2.17.0.jar:?]
	at com.github.oscerd.component.cassandra.CassandraProducer.process(CassandraProducer.java:109) ~[camel-cassandra-2.17.0.jar:?]
	... 24 more
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:18 no viable alternative at input ')' (INSERT INTO test ([)]...)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:132) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:184) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:798) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:617) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1005) ~[cassandra-driver-core-3.0.0.jar:?]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:928) ~[cassandra-driver-core-3.0.0.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) ~[netty-handler-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.33.Final.jar:4.0.33.Final]
	... 1 more
2018-01-16 00:21:44,071 [alhost:21/files] WARN  GenericFileOnCompletion        - Rollback file strategy: org.apache.camel.component.file.strategy.GenericFileRenameProcessStrategy@51d5efde for file: RemoteFile[t5.txt]

**Comment by oscerd** [comment]
Why did you close this?

**Comment by utkarshdeep** [comment]
Posted the issue at the wrong place. I have reposted the issue at the correct place:
[https://github.com/oscerd/camel-cassandra/issues/2](issue)
Sorry for the inconvenience.

**Comment by utkarshdeep** [comment]
Posted the issue at the wrong place. I have reposted the issue at the correct place:
https://github.com/oscerd/camel-cassandra/issues/2
Sorry for the inconvenience.
